import { EventEmitter, Injectable } from '@angular/core';
import { Home } from './home/home';
import { Item } from './home/home';
import { TranslateService } from './translate.service';
import { Observable, of } from 'rxjs';
import { switchMap } from 'rxjs/operators';
import { Popular } from './popular';

@Injectable({
  providedIn: 'root',
})
export class HomeService {
  protected categorysList: Home[] = [
    {
      categorys: [
        'ღუმელის ტენები',
        'ტოსტერის ტენები',
        'გრილის ტენები',
        'თერმოსტატები',
        'ყავის აპარატის ტენები',
        'სამრეწველო ტენები',
        'წყლის გამაცხელებელი ტენები',
        'სარეცხი მანქანის ტენები',
        'ვენტილაციის ტენები',
      ],
      items: [
        {category: 'ღუმელის ტენები',name: 'ღუმელის ტენი',price: 1,description: 'Description for ღუმელის ტენი',image: 'assets/tenebi/Grill/1150-2.jpg',id: 1,code: '1150-2',},
        {category: 'ღუმელის ტენები',name: 'ღუმელის ტენი',price: 1,description: 'Description for ღუმელის ტენი',image: 'assets/tenebi/Grill/1150.jpg',id: 2,code: '1150',},
        {category: 'ღუმელის ტენები',name: 'ღუმელის ტენი',price: 1,description: 'Description for ღუმელის ტენი',image: 'assets/tenebi/Grill/1152.jpg',id: 3,code: '1152',},
        {category: 'ღუმელის ტენები',name: 'ღუმელის ტენი',price: 1,description: 'Description for ღუმელის ტენი',image: 'assets/tenebi/Grill/21142.jpg',id: 4,code: '21142',},
        {category: 'ღუმელის ტენები',name: 'ღუმელის ტენი',price: 1,description: 'Description for ღუმელის ტენი',image: 'assets/tenebi/Grill/22597-2.jpg',id: 5,code: '22597-2',},
        {category: 'ღუმელის ტენები',name: 'ღუმელის ტენი',price: 1,description: 'Description for ღუმელის ტენი',image: 'assets/tenebi/Grill/22781-1.jpg',id: 6,code: '22781-1',},
        {category: 'ღუმელის ტენები',name: 'ღუმელის ტენი',price: 1,description: 'Description for ღუმელის ტენი',image: 'assets/tenebi/Grill/23331-1.jpg',id: 7,code: '23331-1',},
        {category: 'ღუმელის ტენები',name: 'ღუმელის ტენი',price: 1,description: 'Description for ღუმელის ტენი',image: 'assets/tenebi/Grill/23574.jpg',id: 8,code: '23574',},
        {category: 'ღუმელის ტენები',name: 'ღუმელის ტენი',price: 1,description: 'Description for ღუმელის ტენი',image: 'assets/tenebi/Grill/23693.jpg',id: 9,code: '23693',},
        {category: 'ღუმელის ტენები',name: 'ღუმელის ტენი',price: 1,description: 'Description for ღუმელის ტენი',image: 'assets/tenebi/Grill/23806-1.jpg',id: 10,code: '23806-1',},
        {category: 'ღუმელის ტენები',name: 'ღუმელის ტენი',price: 1,description: 'Description for ღუმელის ტენი',image: 'assets/tenebi/Grill/23827.jpg',id: 11,code: '23827',},
        {category: 'ღუმელის ტენები',name: 'ღუმელის ტენი',price: 1,description: 'Description for ღუმელის ტენი',image: 'assets/tenebi/Grill/23888.jpg',id: 12,code: '23888',},
        {category: 'ღუმელის ტენები',name: 'ღუმელის ტენი',price: 1,description: 'Description for ღუმელის ტენი',image: 'assets/tenebi/Grill/24742.jpg',id: 13,code: '24742',},
        {category: 'ღუმელის ტენები',name: 'ღუმელის ტენი',price: 1,description: 'Description for ღუმელის ტენი',image: 'assets/tenebi/Grill/24751.jpg',id: 14,code: '24751',},
        {category: 'ღუმელის ტენები',name: 'ღუმელის ტენი',price: 1,description: 'Description for ღუმელის ტენი',image: 'assets/tenebi/Grill/24800.jpg',id: 15,code: '24800',},
        {category: 'ღუმელის ტენები',name: 'ღუმელის ტენი',price: 1,description: 'Description for ღუმელის ტენი',image: 'assets/tenebi/Grill/24807.jpg',id: 16,code: '24807',},
        {category: 'ღუმელის ტენები',name: 'ღუმელის ტენი',price: 1,description: 'Description for ღუმელის ტენი',image: 'assets/tenebi/Grill/24840.jpg',id: 17,code: '24840',},
        {category: 'ღუმელის ტენები',name: 'ღუმელის ტენი',price: 1,description: 'Description for ღუმელის ტენი',image: 'assets/tenebi/Grill/24999.jpg',id: 18,code: '24999',},
        {category: 'ღუმელის ტენები',name: 'ღუმელის ტენი',price: 1,description: 'Description for ღუმელის ტენი',image: 'assets/tenebi/Grill/25000.jpg',id: 19,code: '25000',},
        {category: 'ღუმელის ტენები',name: 'ღუმელის ტენი',price: 1,description: 'Description for ღუმელის ტენი',image: 'assets/tenebi/Grill/25014.jpg',id: 20,code: '25014',},
        {category: 'ღუმელის ტენები',name: 'ღუმელის ტენი',price: 1,description: 'Description for ღუმელის ტენი',image: 'assets/tenebi/Grill/90616.jpg',id: 21,code: '90616',},
        {category: 'ღუმელის ტენები',name: 'ღუმელის ტენი',price: 1,description: 'Description for ღუმელის ტენი',image: 'assets/tenebi/Grill/93579.jpg',id: 22,code: '93579',},

        {category: 'ტოსტერის ტენები',name: 'ტოსტერის ტენი',price: 1,description: 'Description for ტოსტერის ტენი',image: 'assets/tenebi/Toaster/1021.jpg',id: 23,code: '1021',},
        {category: 'ტოსტერის ტენები',name: 'ტოსტერის ტენი',price: 1,description: 'Description for ტოსტერის ტენი',image: 'assets/tenebi/Toaster/1022.jpg',id: 24,code: '1022',},
        {category: 'ტოსტერის ტენები',name: 'ტოსტერის ტენი',price: 1,description: 'Description for ტოსტერის ტენი',image: 'assets/tenebi/Toaster/1023-B.jpg',id: 25,code: '1023-B',},
        {category: 'ტოსტერის ტენები',name: 'ტოსტერის ტენი',price: 1,description: 'Description for ტოსტერის ტენი',image: 'assets/tenebi/Toaster/1023-K.jpg',id: 26,code: '1023-K',},
        {category: 'ტოსტერის ტენები',name: 'ტოსტერის ტენი',price: 1,description: 'Description for ტოსტერის ტენი',image: 'assets/tenebi/Toaster/1024.jpg',id: 27,code: '1024',},
        {category: 'ტოსტერის ტენები',name: 'ტოსტერის ტენი',price: 1,description: 'Description for ტოსტერის ტენი',image: 'assets/tenebi/Toaster/1025.jpg',id: 28,code: '1025',},
        {category: 'ტოსტერის ტენები',name: 'ტოსტერის ტენი',price: 1,description: 'Description for ტოსტერის ტენი',image: 'assets/tenebi/Toaster/1026.jpg',id: 29,code: '1026',},
        {category: 'ტოსტერის ტენები',name: 'ტოსტერის ტენი',price: 1,description: 'Description for ტოსტერის ტენი',image: 'assets/tenebi/Toaster/1135.jpg',id: 30,code: '1135',},
        {category: 'ტოსტერის ტენები',name: 'ტოსტერის ტენი',price: 1,description: 'Description for ტოსტერის ტენი',image: 'assets/tenebi/Toaster/1136.jpg',id: 31,code: '1136',},
        {category: 'ტოსტერის ტენები',name: 'ტოსტერის ტენი',price: 1,description: 'Description for ტოსტერის ტენი',image: 'assets/tenebi/Toaster/1139.jpg',id: 32,code: '1139',},
        {category: 'ტოსტერის ტენები',name: 'ტოსტერის ტენი',price: 1,description: 'Description for ტოსტერის ტენი',image: 'assets/tenebi/Toaster/1141.jpg',id: 33,code: '1141',},
        {category: 'ტოსტერის ტენები',name: 'ტოსტერის ტენი',price: 1,description: 'Description for ტოსტერის ტენი',image: 'assets/tenebi/Toaster/1149.jpg',id: 34,code: '1149',},
        {category: 'ტოსტერის ტენები',name: 'ტოსტერის ტენი',price: 1,description: 'Description for ტოსტერის ტენი',image: 'assets/tenebi/Toaster/20066.jpg',id: 35,code: '20066',},
        {category: 'ტოსტერის ტენები',name: 'ტოსტერის ტენი',price: 1,description: 'Description for ტოსტერის ტენი',image: 'assets/tenebi/Toaster/20192.jpg',id: 36,code: '20192',},
        {category: 'ტოსტერის ტენები',name: 'ტოსტერის ტენი',price: 1,description: 'Description for ტოსტერის ტენი',image: 'assets/tenebi/Toaster/20248.jpg',id: 37,code: '20248',},
        {category: 'ტოსტერის ტენები',name: 'ტოსტერის ტენი',price: 1,description: 'Description for ტოსტერის ტენი',image: 'assets/tenebi/Toaster/20261.jpg',id: 38,code: '20261',},
        {category: 'ტოსტერის ტენები',name: 'ტოსტერის ტენი',price: 1,description: 'Description for ტოსტერის ტენი',image: 'assets/tenebi/Toaster/21110.jpg',id: 39,code: '21110',},
        {category: 'ტოსტერის ტენები',name: 'ტოსტერის ტენი',price: 1,description: 'Description for ტოსტერის ტენი',image: 'assets/tenebi/Toaster/21669.jpg',id: 40,code: '21669',},
        {category: 'ტოსტერის ტენები',name: 'ტოსტერის ტენი',price: 1,description: 'Description for ტოსტერის ტენი',image: 'assets/tenebi/Toaster/23093.jpg',id: 41,code: '23093',},
        {category: 'ტოსტერის ტენები',name: 'ტოსტერის ტენი',price: 1,description: 'Description for ტოსტერის ტენი',image: 'assets/tenebi/Toaster/23351.jpg',id: 42,code: '23351',},
        {category: 'ტოსტერის ტენები',name: 'ტოსტერის ტენი',price: 1,description: 'Description for ტოსტერის ტენი',image: 'assets/tenebi/Toaster/23352.jpg',id: 43,code: '23352',},
        {category: 'ტოსტერის ტენები',name: 'ტოსტერის ტენი',price: 1,description: 'Description for ტოსტერის ტენი',image: 'assets/tenebi/Toaster/23411.jpg',id: 44,code: '23411',},
        {category: 'ტოსტერის ტენები',name: 'ტოსტერის ტენი',price: 1,description: 'Description for ტოსტერის ტენი',image: 'assets/tenebi/Toaster/23482.jpg',id: 45,code: '23482',},
        {category: 'ტოსტერის ტენები',name: 'ტოსტერის ტენი',price: 1,description: 'Description for ტოსტერის ტენი',image: 'assets/tenebi/Toaster/23669.jpg',id: 46,code: '23669',},
        {category: 'ტოსტერის ტენები',name: 'ტოსტერის ტენი',price: 1,description: 'Description for ტოსტერის ტენი',image: 'assets/tenebi/Toaster/23675.jpg',id: 47,code: '23675',},
        {category: 'ტოსტერის ტენები',name: 'ტოსტერის ტენი',price: 1,description: 'Description for ტოსტერის ტენი',image: 'assets/tenebi/Toaster/23701.jpg',id: 48,code: '23701',},
        {category: 'ტოსტერის ტენები',name: 'ტოსტერის ტენი',price: 1,description: 'Description for ტოსტერის ტენი',image: 'assets/tenebi/Toaster/23729.jpg',id: 49,code: '23729',},
        {category: 'ტოსტერის ტენები',name: 'ტოსტერის ტენი',price: 1,description: 'Description for ტოსტერის ტენი',image: 'assets/tenebi/Toaster/23730.jpg',id: 50,code: '23730',},
        {category: 'ტოსტერის ტენები',name: 'ტოსტერის ტენი',price: 1,description: 'Description for ტოსტერის ტენი',image: 'assets/tenebi/Toaster/24094.jpg',id: 51,code: '24094',},
        {category: 'ტოსტერის ტენები',name: 'ტოსტერის ტენი',price: 1,description: 'Description for ტოსტერის ტენი',image: 'assets/tenebi/Toaster/25155.jpg',id: 52,code: '25155',},
        {category: 'ტოსტერის ტენები',name: 'ტოსტერის ტენი',price: 1,description: 'Description for ტოსტერის ტენი',image: 'assets/tenebi/Toaster/25156.jpg',id: 53,code: '25156',},
        {category: 'ტოსტერის ტენები',name: 'ტოსტერის ტენი',price: 1,description: 'Description for ტოსტერის ტენი',image: 'assets/tenebi/Toaster/92336.jpg',id: 54,code: '92336',},
        {category: 'ტოსტერის ტენები',name: 'ტოსტერის ტენი',price: 1,description: 'Description for ტოსტერის ტენი',image: 'assets/tenebi/Toaster/92337.jpg',id: 55,code: '92337',},
        {category: 'ტოსტერის ტენები',name: 'ტოსტერის ტენი',price: 1,description: 'Description for ტოსტერის ტენი',image: 'assets/tenebi/Toaster/93358.jpg',id: 56,code: '93358',},

        {category: 'გრილის ტენები',name: 'გრილის ტენი',price: 1,description: 'Description for გრილის ტენი',image: 'assets/tenebi/Grill/1150-2.jpg',id: 57,code: '1150-2',},
        {category: 'გრილის ტენები',name: 'გრილის ტენი',price: 1,description: 'Description for გრილის ტენი',image: 'assets/tenebi/Grill/1150.jpg',id: 58,code: '1150',},
        {category: 'გრილის ტენები',name: 'გრილის ტენი',price: 1,description: 'Description for გრილის ტენი',image: 'assets/tenebi/Grill/1152.jpg',id: 59,code: '1152',},
        {category: 'გრილის ტენები',name: 'გრილის ტენი',price: 1,description: 'Description for გრილის ტენი',image: 'assets/tenebi/Grill/21142.jpg',id: 60,code: '21142',},
        {category: 'გრილის ტენები',name: 'გრილის ტენი',price: 1,description: 'Description for გრილის ტენი',image: 'assets/tenebi/Grill/22597-2.jpg',id: 61,code: '22597-2',},
        {category: 'გრილის ტენები',name: 'გრილის ტენი',price: 1,description: 'Description for გრილის ტენი',image: 'assets/tenebi/Grill/22781-1.jpg',id: 62,code: '22781-1',},
        {category: 'გრილის ტენები',name: 'გრილის ტენი',price: 1,description: 'Description for გრილის ტენი',image: 'assets/tenebi/Grill/23331-1.jpg',id: 63,code: '23331-1',},
        {category: 'გრილის ტენები',name: 'გრილის ტენი',price: 1,description: 'Description for გრილის ტენი',image: 'assets/tenebi/Grill/23574.jpg',id: 64,code: '23574',},
        {category: 'გრილის ტენები',name: 'გრილის ტენი',price: 1,description: 'Description for გრილის ტენი',image: 'assets/tenebi/Grill/23693.jpg',id: 65,code: '23693',},
        {category: 'გრილის ტენები',name: 'გრილის ტენი',price: 1,description: 'Description for გრილის ტენი',image: 'assets/tenebi/Grill/23806-1.jpg',id: 66,code: '23806-1',},
        {category: 'გრილის ტენები',name: 'გრილის ტენი',price: 1,description: 'Description for გრილის ტენი',image: 'assets/tenebi/Grill/23827.jpg',id: 67,code: '23827',},
        {category: 'გრილის ტენები',name: 'გრილის ტენი',price: 1,description: 'Description for გრილის ტენი',image: 'assets/tenebi/Grill/23888.jpg',id: 68,code: '23888',},
        {category: 'გრილის ტენები',name: 'გრილის ტენი',price: 1,description: 'Description for გრილის ტენი',image: 'assets/tenebi/Grill/24742.jpg',id: 69,code: '24742',},
        {category: 'გრილის ტენები',name: 'გრილის ტენი',price: 1,description: 'Description for გრილის ტენი',image: 'assets/tenebi/Grill/24751.jpg',id: 70,code: '24751',},
        {category: 'გრილის ტენები',name: 'გრილის ტენი',price: 1,description: 'Description for გრილის ტენი',image: 'assets/tenebi/Grill/24800.jpg',id: 71,code: '24800', },
        {category: 'გრილის ტენები',name: 'გრილის ტენი',price: 1,description: 'Description for გრილის ტენი',image: 'assets/tenebi/Grill/24807.jpg',id: 72,code: '24807', },
        {category: 'გრილის ტენები',name: 'გრილის ტენი',price: 1,description: 'Description for გრილის ტენი',image: 'assets/tenebi/Grill/24840.jpg',id: 73,code: '24840', },
        {category: 'გრილის ტენები',name: 'გრილის ტენი',price: 1,description: 'Description for გრილის ტენი',image: 'assets/tenebi/Grill/24999.jpg',id: 74,code: '24999', },
        {category: 'გრილის ტენები',name: 'გრილის ტენი',price: 1,description: 'Description for გრილის ტენი',image: 'assets/tenebi/Grill/25000.jpg',id: 75,code: '25000', },
        {category: 'გრილის ტენები',name: 'გრილის ტენი',price: 1,description: 'Description for გრილის ტენი',image: 'assets/tenebi/Grill/25014.jpg',id: 76,code: '25014',},
        {category: 'გრილის ტენები',name: 'გრილის ტენი',price: 1,description: 'Description for გრილის ტენი',image: 'assets/tenebi/Grill/90616.jpg',id: 77,code: '90616',},
        {category: 'გრილის ტენები',name: 'გრილის ტენი',price: 1,description: 'Description for გრილის ტენი',image: 'assets/tenebi/Grill/93579.jpg',id: 78,code: '93579',},

        {category: 'თერმოსტატები',name: 'თერმოსტატი',price: 1,description: 'Description for თერმოსტატი',image: 'assets/tenebi/Termostat/1062K.jpg',id: 79,code: '1062K',},
        {category: 'თერმოსტატები',name: 'თერმოსტატი',price: 1,description: 'Description for თერმოსტატი',image: 'assets/tenebi/Termostat/23990.jpg',id: 80,code: '23990',},
        {category: 'თერმოსტატები',name: 'თერმოსტატი',price: 1,description: 'Description for თერმოსტატი',image: 'assets/tenebi/Termostat/91079.jpg',id: 81,code: '91079',},
        {category: 'თერმოსტატები',name: 'თერმოსტატი',price: 1,description: 'Description for თერმოსტატი',image: 'assets/tenebi/Termostat/91694-4.jpg',id: 82,code: '91694-4',},
        {category: 'თერმოსტატები',name: 'თერმოსტატი',price: 1,description: 'Description for თერმოსტატი',image: 'assets/tenebi/Termostat/92588.jpg',id: 83,code: '92588',},
        {category: 'თერმოსტატები',name: 'თერმოსტატი',price: 1,description: 'Description for თერმოსტატი',image: 'assets/tenebi/Termostat/92647.jpg',id: 84,code: '92647',},
        {category: 'თერმოსტატები',name: 'თერმოსტატი',price: 1,description: 'Description for თერმოსტატი',image: 'assets/tenebi/Termostat/92892.jpg',id: 85,code: '92892',},
        {category: 'თერმოსტატები',name: 'თერმოსტატი',price: 1,description: 'Description for თერმოსტატი',image: 'assets/tenebi/Termostat/92937.jpg',id: 86,code: '92937',},
        {category: 'თერმოსტატები',name: 'თერმოსტატი',price: 1,description: 'Description for თერმოსტატი',image: 'assets/tenebi/Termostat/93056.jpg',id: 87,code: '93056',},
        {category: 'თერმოსტატები',name: 'თერმოსტატი',price: 1,description: 'Description for თერმოსტატი',image: 'assets/tenebi/Termostat/93475.jpg',id: 88,code: '93475',},
        {category: 'თერმოსტატები',name: 'თერმოსტატი',price: 1,description: 'Description for თერმოსტატი',image: 'assets/tenebi/Termostat/93511.jpg',id: 89,code: '93511',},
        {category: 'თერმოსტატები',name: 'თერმოსტატი',price: 1,description: 'Description for თერმოსტატი',image: 'assets/tenebi/Termostat/93512.jpg',id: 90,code: '93512',},
        {category: 'თერმოსტატები',name: 'თერმოსტატი',price: 1,description: 'Description for თერმოსტატი',image: 'assets/tenebi/Termostat/93513.jpg',id: 91,code: '93513',},
        {category: 'თერმოსტატები',name: 'თერმოსტატი',price: 1,description: 'Description for თერმოსტატი',image: 'assets/tenebi/Termostat/93545.jpg',id: 92,code: '93545',},
        {category: 'თერმოსტატები',name: 'თერმოსტატი',price: 1,description: 'Description for თერმოსტატი',image: 'assets/tenebi/Termostat/93578.jpg',id: 93,code: '93578',},
        {category: 'თერმოსტატები',name: 'თერმოსტატი',price: 1,description: 'Description for თერმოსტატი',image: 'assets/tenebi/Termostat/RTC10-1612.jpg',id: 94,code: 'RTC10-1612',},
        {category: 'თერმოსტატები',name: 'თერმოსტატი',price: 1,description: 'Description for თერმოსტატი',image: 'assets/tenebi/Termostat/RTD10-28.jpg',id: 95,code: 'RTD10-28',},
        {category: 'თერმოსტატები',name: 'თერმოსტატი',price: 1,description: 'Description for თერმოსტატი',image: 'assets/tenebi/Termostat/TR-1-7027.jpg',id: 96,code: 'TR-1-7027',},
        {category: 'თერმოსტატები',name: 'თერმოსტატი',price: 1,description: 'Description for თერმოსტატი',image: 'assets/tenebi/Termostat/TRS-657527.jpg',id: 97,code: 'TRS-657527',},


        {category: 'ყავის აპარატის ტენები',name: 'ყავის აპარატი',price: 1,description: 'Description for ყავის აპარატი',image: 'assets/tenebi/Coffe/1055.jpg',id: 98,code: '1055',},
        {category: 'ყავის აპარატის ტენები',name: 'ყავის აპარატი',price: 1,description: 'Description for ყავის აპარატი',image: 'assets/tenebi/Coffe/1056-A.jpg',id: 99,code:'1056-A',},
        {category: 'ყავის აპარატის ტენები',name: 'ყავის აპარატი',price: 1,description: 'Description for ყავის აპარატი',image: 'assets/tenebi/Coffe/1056-B.jpg',id: 100,code:'1056-B',},
        {category: 'ყავის აპარატის ტენები',name: 'ყავის აპარატი',price: 1,description: 'Description for ყავის აპარატი',image: 'assets/tenebi/Coffe/1056-C.jpg',id: 101,code:'1056-C',},
        {category: 'ყავის აპარატის ტენები',name: 'ყავის აპარატი',price: 1,description: 'Description for ყავის აპარატი',image: 'assets/tenebi/Coffe/1132-B.jpg',id: 102,code:'1132-B',},
        {category: 'ყავის აპარატის ტენები',name: 'ყავის აპარატი',price: 1,description: 'Description for ყავის აპარატი',image: 'assets/tenebi/Coffe/1133-B.jpg',id: 103,code:'1133-B',},
        {category: 'ყავის აპარატის ტენები',name: 'ყავის აპარატი',price: 1,description: 'Description for ყავის აპარატი',image: 'assets/tenebi/Coffe/1137K.jpg',id: 104,code:'1137K',},
        {category: 'ყავის აპარატის ტენები',name: 'ყავის აპარატი',price: 1,description: 'Description for ყავის აპარატი',image: 'assets/tenebi/Coffe/1140.jpg',id: 105,code: '1140',},
        {category: 'ყავის აპარატის ტენები',name: 'ყავის აპარატი',price: 1,description: 'Description for ყავის აპარატი',image: 'assets/tenebi/Coffe/1142-B.jpg',id: 106,code: '1142-B',},
        {category: 'ყავის აპარატის ტენები',name: 'ყავის აპარატი',price: 1,description: 'Description for ყავის აპარატი',image: 'assets/tenebi/Coffe/20143.jpg',id: 107,code: '20143',},
        {category: 'ყავის აპარატის ტენები',name: 'ყავის აპარატი',price: 1,description: 'Description for ყავის აპარატი',image: 'assets/tenebi/Coffe/20161-1.jpg',id: 108,code: '20161-1',},
        {category: 'ყავის აპარატის ტენები',name: 'ყავის აპარატი',price: 1,description: 'Description for ყავის აპარატი',image: 'assets/tenebi/Coffe/20352.jpg',id: 109,code: '20352',},
        {category: 'ყავის აპარატის ტენები',name: 'ყავის აპარატი',price: 1,description: 'Description for ყავის აპარატი',image: 'assets/tenebi/Coffe/21341.jpg',id: 110,code: '21341',},
        {category: 'ყავის აპარატის ტენები',name: 'ყავის აპარატი',price: 1,description: 'Description for ყავის აპარატი',image: 'assets/tenebi/Coffe/21342-1.jpg',id: 111,code: '21342-1',},
        {category: 'ყავის აპარატის ტენები',name: 'ყავის აპარატი',price: 1,description: 'Description for ყავის აპარატი',image: 'assets/tenebi/Coffe/21342.jpg',id: 112,code: '21342',},
        {category: 'ყავის აპარატის ტენები',name: 'ყავის აპარატი',price: 1,description: 'Description for ყავის აპარატი',image: 'assets/tenebi/Coffe/23146.jpg',id: 113,code: '23146',},
        {category: 'ყავის აპარატის ტენები',name: 'ყავის აპარატი',price: 1,description: 'Description for ყავის აპარატი',image: 'assets/tenebi/Coffe/23671.jpg',id: 114,code: '23671',},
        {category: 'ყავის აპარატის ტენები',name: 'ყავის აპარატი',price: 1,description: 'Description for ყავის აპარატი',image: 'assets/tenebi/Coffe/23676.jpg',id: 115,code: '23676',},
        {category: 'ყავის აპარატის ტენები',name: 'ყავის აპარატი',price: 1,description: 'Description for ყავის აპარატი',image: 'assets/tenebi/Coffe/23677.jpg',id: 116,code: '23677',},
        {category: 'ყავის აპარატის ტენები',name: 'ყავის აპარატი',price: 1,description: 'Description for ყავის აპარატი',image: 'assets/tenebi/Coffe/23681-B.jpg',id: 117,code: '23681-B',},
        {category: 'ყავის აპარატის ტენები',name: 'ყავის აპარატი',price: 1,description: 'Description for ყავის აპარატი',image: 'assets/tenebi/Coffe/23681-K.jpg',id: 118,code: '23681-K',},
        {category: 'ყავის აპარატის ტენები',name: 'ყავის აპარატი',price: 1,description: 'Description for ყავის აპარატი',image: 'assets/tenebi/Coffe/24533.jpg',id: 119,code: '24533',},
        {category: 'ყავის აპარატის ტენები',name: 'ყავის აპარატი',price: 1,description: 'Description for ყავის აპარატი',image: 'assets/tenebi/Coffe/24534.jpg',id: 120,code: '24534',},
        {category: 'ყავის აპარატის ტენები',name: 'ყავის აპარატი',price: 1,description: 'Description for ყავის აპარატი',image: 'assets/tenebi/Coffe/24535.jpg',id: 121,code: '24535',},
        {category: 'ყავის აპარატის ტენები',name: 'ყავის აპარატი',price: 1,description: 'Description for ყავის აპარატი',image: 'assets/tenebi/Coffe/24538.jpg',id: 122,code: '24538',},
        {category: 'ყავის აპარატის ტენები',name: 'ყავის აპარატი',price: 1,description: 'Description for ყავის აპარატი',image: 'assets/tenebi/Coffe/24611.jpg',id: 123,code: '24611',},
        {category: 'ყავის აპარატის ტენები',name: 'ყავის აპარატი',price: 1,description: 'Description for ყავის აპარატი',image: 'assets/tenebi/Coffe/91677.jpg',id: 124,code: '91677',},
        {category: 'ყავის აპარატის ტენები',name: 'ყავის აპარატი',price: 1,description: 'Description for ყავის აპარატი',image: 'assets/tenebi/Coffe/91681.jpg',id: 125,code: '91681',},
        {category: 'ყავის აპარატის ტენები',name: 'ყავის აპარატი',price: 1,description: 'Description for ყავის აპარატი',image: 'assets/tenebi/Coffe/91682.jpg',id: 126,code: '91682',},
        {category: 'ყავის აპარატის ტენები',name: 'ყავის აპარატი',price: 1,description: 'Description for ყავის აპარატი',image: 'assets/tenebi/Coffe/91683.jpg',id: 127,code: '91683',},
        {category: 'ყავის აპარატის ტენები',name: 'ყავის აპარატი',price: 1,description: 'Description for ყავის აპარატი',image: 'assets/tenebi/Coffe/91684.jpg',id: 128,code: '91684',},
        {category: 'ყავის აპარატის ტენები',name: 'ყავის აპარატი',price: 1,description: 'Description for ყავის აპარატი',image: 'assets/tenebi/Coffe/92272.jpg',id: 129,code: '92272',},
        {category: 'ყავის აპარატის ტენები',name: 'ყავის აპარატი',price: 1,description: 'Description for ყავის აპარატი',image: 'assets/tenebi/Coffe/92273.jpg',id: 130,code: '92273',},
        {category: 'ყავის აპარატის ტენები',name: 'ყავის აპარატი',price: 1,description: 'Description for ყავის აპარატი',image: 'assets/tenebi/Coffe/92342.jpg',id: 131,code: '92342',},
        {category: 'ყავის აპარატის ტენები',name: 'ყავის აპარატი',price: 1,description: 'Description for ყავის აპარატი',image: 'assets/tenebi/Coffe/92424.jpg',id: 132,code: '92424',},
        {category: 'ყავის აპარატის ტენები',name: 'ყავის აპარატი',price: 1,description: 'Description for ყავის აპარატი',image: 'assets/tenebi/Coffe/92481-1.jpg',id: 133,code: '92481-1',},
        {category: 'ყავის აპარატის ტენები',name: 'ყავის აპარატი',price: 1,description: 'Description for ყავის აპარატი',image: 'assets/tenebi/Coffe/92568B.jpg',id: 134,code: '92568B',},
        {category: 'ყავის აპარატის ტენები',name: 'ყავის აპარატი',price: 1,description: 'Description for ყავის აპარატი',image: 'assets/tenebi/Coffe/92571.jpg',id: 135,code: '92571',},
        {category: 'ყავის აპარატის ტენები',name: 'ყავის აპარატი',price: 1,description: 'Description for ყავის აპარატი',image: 'assets/tenebi/Coffe/92654.jpg',id: 136,code: '92654',},
        {category: 'ყავის აპარატის ტენები',name: 'ყავის აპარატი',price: 1,description: 'Description for ყავის აპარატი',image: 'assets/tenebi/Coffe/92655.jpg',id: 137,code: '92655',},
        {category: 'ყავის აპარატის ტენები',name: 'ყავის აპარატი',price: 1,description: 'Description for ყავის აპარატი',image: 'assets/tenebi/Coffe/92827.jpg',id: 138,code: '92827',},
        {category: 'ყავის აპარატის ტენები',name: 'ყავის აპარატი',price: 1,description: 'Description for ყავის აპარატი',image: 'assets/tenebi/Coffe/93354.jpg',id: 139,code: '93354',},
        {category: 'ყავის აპარატის ტენები',name: 'ყავის აპარატი',price: 1,description: 'Description for ყავის აპარატი',image: 'assets/tenebi/Coffe/93356.jpg',id: 140,code: '93356',},
        {category: 'ყავის აპარატის ტენები',name: 'ყავის აპარატი',price: 1,description: 'Description for ყავის აპარატი',image: 'assets/tenebi/Coffe/93364.jpg',id: 141,code: '93364',},
        {category: 'ყავის აპარატის ტენები',name: 'ყავის აპარატი',price: 1,description: 'Description for ყავის აპარატი',image: 'assets/tenebi/Coffe/93379.jpg',id: 142,code: '93379',},
        {category: 'ყავის აპარატის ტენები',name: 'ყავის აპარატი',price: 1,description: 'Description for ყავის აპარატი',image: 'assets/tenebi/Coffe/93469.jpg',id: 143,code: '93469',},
        {category: 'ყავის აპარატის ტენები',name: 'ყავის აპარატი',price: 1,description: 'Description for ყავის აპარატი',image: 'assets/tenebi/Coffe/93697.jpg',id: 144,code: '93697',},
        {category: 'ყავის აპარატის ტენები',name: 'ყავის აპარატი',price: 1,description: 'Description for ყავის აპარატი',image: 'assets/tenebi/Coffe/93701.jpg',id: 145,code: '93701',},
        {category: 'ყავის აპარატის ტენები',name: 'ყავის აპარატი',price: 1,description: 'Description for ყავის აპარატი',image: 'assets/tenebi/Coffe/93704.jpg',id: 146,code: '93704',},

        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/1059.jpg',id: 147,code: '1059',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/1134-1.jpg',id: 148,code: '1134-1',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/1134.jpg',id: 149,code: '1134',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/20186.jpg',id: 150,code: '20186',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/20198.jpg',id: 151,code: '20198',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/20250.jpg',id: 152,code: '20250',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/20251-3D.jpg',id: 152,code: '20251-3D',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/20251-3E.jpg',id: 153,code: '20251-3E',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/20253.jpg',id: 154,code: '20253',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/20298.jpg',id: 155,code: '20298',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/20333.jpg',id: 156,code: '20333',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/20334.jpg',id: 157,code: '20334',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/20335.jpg',id: 158,code: '20335',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/20338.jpg',id: 159,code: '20338',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/20357.jpg',id: 160,code: '20357',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/23672-1.jpg',id: 161,code: '23672-1',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/23673.jpg',id: 162,code: '23673',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/23691.jpg',id: 163,code: '23691',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/23692.jpg',id: 164,code: '23692',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/23733.jpg',id: 165,code: '23733',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/24599.jpg',id: 166,code: '24599',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/25021.jpg',id: 167,code: '25021',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/25030.jpg',id: 168,code: '25030',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/25039.jpg',id: 169,code: '25039',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/25043.jpg',id: 170,code: '25043',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/25046.jpg',id: 171,code: '25046',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/90825.jpg',id: 172,code: '90825',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/90963.jpg',id: 173,code: '90963',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/91008.jpg',id: 174,code: '91008',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/91281.jpg',id: 175,code: '91281',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/91293.jpg',id: 176,code: '91293',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/91588.jpg',id: 177,code: '91588',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/91976.jpg',id: 178,code: '91976',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/92136.jpg',id: 179,code: '92136',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/92352.jpg',id: 180,code: '92352',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/92649.jpg',id: 181,code: '92649',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/92650.jpg',id: 182,code: '92650',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/92653.jpg',id: 183,code: '92653',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/92657.jpg',id: 184,code: '92657',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/92674.jpg',id: 185,code: '92674',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/92705.jpg',id: 186,code: '92705',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/92706.jpg',id: 187,code: '92706',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/92707.jpg',id: 188,code: '92707',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/92708.jpg',id: 189,code: '92708',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/92711.jpg',id: 190,code: '92711',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/92764.jpg',id: 191,code: '92764',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/92831.jpg',id: 192,code: '92831',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/93025.jpg',id: 193,code: '93025',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/93355.jpg',id: 194,code: '93355',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/93357.jpg',id: 195,code: '93357',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/93359.jpg',id: 196,code: '93359',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/93363.jpg',id: 197,code: '93363',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/93374.jpg',id: 198,code: '93374',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/93468.jpg',id: 199,code: '93468',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/93505.jpg',id: 200,code: '93505',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/93514.jpg',id: 201,code: '93514',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/93580.jpg',id: 202,code: '93580',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/93581.jpg',id: 203,code: '93581',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/93582.jpg',id: 204,code: '93582',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/93612.jpg',id: 205,code: '93612',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/93614.jpg',id: 206,code: '93614',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/93617.jpg',id: 207,code: '93617',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/93618.jpg',id: 208,code: '93618',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/93619.jpg',id: 209,code: '93619',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/93620.jpg',id: 210,code: '93620',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/93621.jpg',id: 211,code: '93621',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/93622.jpg',id: 212,code: '93622',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/93625.jpg',id: 213,code: '93625',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/93626.jpg',id: 214,code: '93626',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/93628.jpg',id: 215,code: '93628',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/93629.jpg',id: 216,code: '93629',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/93630.jpg',id: 217,code: '93630',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/93631.jpg',id: 218,code: '93631',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/93632.jpg',id: 219,code: '93632',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/93633.jpg',id: 220,code: '93633',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/93634.jpg',id: 221,code: '93634',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/93636.jpg',id: 222,code: '93636',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/93637.jpg',id: 223,code: '93637',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/93638.jpg',id: 224,code: '93638',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/93641.jpg',id: 225,code: '93641',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/93661.jpg',id: 226,code: '93661',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/93664.jpg',id: 227,code: '93664',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/93668.jpg',id: 228,code: '93668',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/93669.jpg',id: 229,code: '93669',},
        {category: 'სამრეწველო ტენები', name: 'სამრეწველო ტენი',price: 1,description: 'Description for სამრეწველო ტენი',image: 'assets/tenebi/Industrial/93742.jpg',id: 230,code: '93742',},

        {category: 'წყლის გამაცხელებელი ტენები',name: 'წყლის გამაცხელებელი ტენი',price: 1,description: 'Description for წყლის გამაცხელებელი ტენი',image: 'assets/tenebi/Water Heating/1031.jpg',id: 231,code: '1031',},
        {category: 'წყლის გამაცხელებელი ტენები',name: 'წყლის გამაცხელებელი ტენი',price: 1,description: 'Description for წყლის გამაცხელებელი ტენი',image: 'assets/tenebi/Water Heating/1031B.jpg',id: 232,code: '1031B',},
        {category: 'წყლის გამაცხელებელი ტენები',name: 'წყლის გამაცხელებელი ტენი',price: 1,description: 'Description for წყლის გამაცხელებელი ტენი',image: 'assets/tenebi/Water Heating/1032-2.jpg',id: 233,code: '1032-2',},
        {category: 'წყლის გამაცხელებელი ტენები',name: 'წყლის გამაცხელებელი ტენი',price: 1,description: 'Description for წყლის გამაცხელებელი ტენი',image: 'assets/tenebi/Water Heating/1032-4.jpg',id: 234,code: '1032-4',},
        {category: 'წყლის გამაცხელებელი ტენები',name: 'წყლის გამაცხელებელი ტენი',price: 1,description: 'Description for წყლის გამაცხელებელი ტენი',image: 'assets/tenebi/Water Heating/1032.jpg',id: 235,code: '1032',},
        {category: 'წყლის გამაცხელებელი ტენები',name: 'წყლის გამაცხელებელი ტენი',price: 1,description: 'Description for წყლის გამაცხელებელი ტენი',image: 'assets/tenebi/Water Heating/20180.jpg',id: 236,code: '20180',},
        {category: 'წყლის გამაცხელებელი ტენები',name: 'წყლის გამაცხელებელი ტენი',price: 1,description: 'Description for წყლის გამაცხელებელი ტენი',image: 'assets/tenebi/Water Heating/20187.jpg',id: 237,code: '20187',},
        {category: 'წყლის გამაცხელებელი ტენები',name: 'წყლის გამაცხელებელი ტენი',price: 1,description: 'Description for წყლის გამაცხელებელი ტენი',image: 'assets/tenebi/Water Heating/20223.jpg',id: 238,code: '20223',},
        {category: 'წყლის გამაცხელებელი ტენები',name: 'წყლის გამაცხელებელი ტენი',price: 1,description: 'Description for წყლის გამაცხელებელი ტენი',image: 'assets/tenebi/Water Heating/21951.jpg',id: 239,code: '21951',},
        {category: 'წყლის გამაცხელებელი ტენები',name: 'წყლის გამაცხელებელი ტენი',price: 1,description: 'Description for წყლის გამაცხელებელი ტენი',image: 'assets/tenebi/Water Heating/22293.jpg',id: 240,code: '22293',},
        {category: 'წყლის გამაცხელებელი ტენები',name: 'წყლის გამაცხელებელი ტენი',price: 1,description: 'Description for წყლის გამაცხელებელი ტენი',image: 'assets/tenebi/Water Heating/22821.jpg',id: 241,code: '22821',},
        {category: 'წყლის გამაცხელებელი ტენები',name: 'წყლის გამაცხელებელი ტენი',price: 1,description: 'Description for წყლის გამაცხელებელი ტენი',image: 'assets/tenebi/Water Heating/23302.jpg',id: 242,code: '23302',},
        {category: 'წყლის გამაცხელებელი ტენები',name: 'წყლის გამაცხელებელი ტენი',price: 1,description: 'Description for წყლის გამაცხელებელი ტენი',image: 'assets/tenebi/Water Heating/23378-B.jpg',id: 243,code: '23378-B',},
        {category: 'წყლის გამაცხელებელი ტენები',name: 'წყლის გამაცხელებელი ტენი',price: 1,description: 'Description for წყლის გამაცხელებელი ტენი',image: 'assets/tenebi/Water Heating/23378-K.jpg',id: 244,code: '23378-K',},
        {category: 'წყლის გამაცხელებელი ტენები',name: 'წყლის გამაცხელებელი ტენი',price: 1,description: 'Description for წყლის გამაცხელებელი ტენი',image: 'assets/tenebi/Water Heating/23398.jpg',id: 245,code: '23398',},
        {category: 'წყლის გამაცხელებელი ტენები',name: 'წყლის გამაცხელებელი ტენი',price: 1,description: 'Description for წყლის გამაცხელებელი ტენი',image: 'assets/tenebi/Water Heating/23541.jpg',id: 246,code: '23541',},
        {category: 'წყლის გამაცხელებელი ტენები',name: 'წყლის გამაცხელებელი ტენი',price: 1,description: 'Description for წყლის გამაცხელებელი ტენი',image: 'assets/tenebi/Water Heating/24483.jpg',id: 247,code: '24483',},
        {category: 'წყლის გამაცხელებელი ტენები',name: 'წყლის გამაცხელებელი ტენი',price: 1,description: 'Description for წყლის გამაცხელებელი ტენი',image: 'assets/tenebi/Water Heating/91131.jpg',id: 248,code: '91131',},
        {category: 'წყლის გამაცხელებელი ტენები',name: 'წყლის გამაცხელებელი ტენი',price: 1,description: 'Description for წყლის გამაცხელებელი ტენი',image: 'assets/tenebi/Water Heating/92035.jpg',id: 249,code: '92035',},
        {category: 'წყლის გამაცხელებელი ტენები',name: 'წყლის გამაცხელებელი ტენი',price: 1,description: 'Description for წყლის გამაცხელებელი ტენი',image: 'assets/tenebi/Water Heating/92036.jpg',id: 250,code: '92036',},
        {category: 'წყლის გამაცხელებელი ტენები',name: 'წყლის გამაცხელებელი ტენი',price: 1,description: 'Description for წყლის გამაცხელებელი ტენი',image: 'assets/tenebi/Water Heating/92295.jpg',id: 251,code: '92295',},
        {category: 'წყლის გამაცხელებელი ტენები',name: 'წყლის გამაცხელებელი ტენი',price: 1,description: 'Description for წყლის გამაცხელებელი ტენი',image: 'assets/tenebi/Water Heating/92431.jpg',id: 252,code: '92431',},
        {category: 'წყლის გამაცხელებელი ტენები',name: 'წყლის გამაცხელებელი ტენი',price: 1,description: 'Description for წყლის გამაცხელებელი ტენი',image: 'assets/tenebi/Water Heating/92461-1.jpg',id: 253,code: '92461-1',},
        {category: 'წყლის გამაცხელებელი ტენები',name: 'წყლის გამაცხელებელი ტენი',price: 1,description: 'Description for წყლის გამაცხელებელი ტენი',image: 'assets/tenebi/Water Heating/92601.jpg',id: 254,code: '92601',},
        {category: 'წყლის გამაცხელებელი ტენები',name: 'წყლის გამაცხელებელი ტენი',price: 1,description: 'Description for წყლის გამაცხელებელი ტენი',image: 'assets/tenebi/Water Heating/92602.jpg',id: 255,code: '92602',},
        {category: 'წყლის გამაცხელებელი ტენები',name: 'წყლის გამაცხელებელი ტენი',price: 1,description: 'Description for წყლის გამაცხელებელი ტენი',image: 'assets/tenebi/Water Heating/92603.jpg',id: 256,code: '92603',},
        {category: 'წყლის გამაცხელებელი ტენები',name: 'წყლის გამაცხელებელი ტენი',price: 1,description: 'Description for წყლის გამაცხელებელი ტენი',image: 'assets/tenebi/Water Heating/92604.jpg',id: 257,code: '92604',},
        {category: 'წყლის გამაცხელებელი ტენები',name: 'წყლის გამაცხელებელი ტენი',price: 1,description: 'Description for წყლის გამაცხელებელი ტენი',image: 'assets/tenebi/Water Heating/92613.jpg',id: 258,code: '92613',},
        {category: 'წყლის გამაცხელებელი ტენები',name: 'წყლის გამაცხელებელი ტენი',price: 1,description: 'Description for წყლის გამაცხელებელი ტენი',image: 'assets/tenebi/Water Heating/92616.jpg',id: 259,code: '92616',},
        {category: 'წყლის გამაცხელებელი ტენები',name: 'წყლის გამაცხელებელი ტენი',price: 1,description: 'Description for წყლის გამაცხელებელი ტენი',image: 'assets/tenebi/Water Heating/92660.jpg',id: 260,code: '92660',},
        {category: 'წყლის გამაცხელებელი ტენები',name: 'წყლის გამაცხელებელი ტენი',price: 1,description: 'Description for წყლის გამაცხელებელი ტენი',image: 'assets/tenebi/Water Heating/92932.jpg',id: 261,code: '92932',},
        {category: 'წყლის გამაცხელებელი ტენები',name: 'წყლის გამაცხელებელი ტენი',price: 1,description: 'Description for წყლის გამაცხელებელი ტენი',image: 'assets/tenebi/Water Heating/92933.jpg',id: 262,code: '92933',},
        {category: 'წყლის გამაცხელებელი ტენები',name: 'წყლის გამაცხელებელი ტენი',price: 1,description: 'Description for წყლის გამაცხელებელი ტენი',image: 'assets/tenebi/Water Heating/92961.jpg',id: 263,code: '92961',},
        {category: 'წყლის გამაცხელებელი ტენები',name: 'წყლის გამაცხელებელი ტენი',price: 1,description: 'Description for წყლის გამაცხელებელი ტენი',image: 'assets/tenebi/Water Heating/92970.jpg',id: 264,code: '92970',},
        {category: 'წყლის გამაცხელებელი ტენები',name: 'წყლის გამაცხელებელი ტენი',price: 1,description: 'Description for წყლის გამაცხელებელი ტენი',image: 'assets/tenebi/Water Heating/92998.jpg',id: 265,code: '92998',},
        {category: 'წყლის გამაცხელებელი ტენები',name: 'წყლის გამაცხელებელი ტენი',price: 1,description: 'Description for წყლის გამაცხელებელი ტენი',image: 'assets/tenebi/Water Heating/93055.jpg',id: 266,code: '93055',},
        {category: 'წყლის გამაცხელებელი ტენები',name: 'წყლის გამაცხელებელი ტენი',price: 1,description: 'Description for წყლის გამაცხელებელი ტენი',image: 'assets/tenebi/Water Heating/93265.jpg',id: 267,code: '93265',},
        {category: 'წყლის გამაცხელებელი ტენები',name: 'წყლის გამაცხელებელი ტენი',price: 1,description: 'Description for წყლის გამაცხელებელი ტენი',image: 'assets/tenebi/Water Heating/93265B.jpg',id: 268,code: '93265B',},
        {category: 'წყლის გამაცხელებელი ტენები',name: 'წყლის გამაცხელებელი ტენი',price: 1,description: 'Description for წყლის გამაცხელებელი ტენი',image: 'assets/tenebi/Water Heating/93267.jpg',id: 269,code: '93267',},
        {category: 'წყლის გამაცხელებელი ტენები',name: 'წყლის გამაცხელებელი ტენი',price: 1,description: 'Description for წყლის გამაცხელებელი ტენი',image: 'assets/tenebi/Water Heating/93267B.jpg',id: 270,code: '93267B',},
        {category: 'წყლის გამაცხელებელი ტენები',name: 'წყლის გამაცხელებელი ტენი',price: 1,description: 'Description for წყლის გამაცხელებელი ტენი',image: 'assets/tenebi/Water Heating/93268.jpg',id: 271,code: '93268',},
        {category: 'წყლის გამაცხელებელი ტენები',name: 'წყლის გამაცხელებელი ტენი',price: 1,description: 'Description for წყლის გამაცხელებელი ტენი',image: 'assets/tenebi/Water Heating/93268B.jpg',id: 272,code: '93268B',},
        {category: 'წყლის გამაცხელებელი ტენები',name: 'წყლის გამაცხელებელი ტენი',price: 1,description: 'Description for წყლის გამაცხელებელი ტენი',image: 'assets/tenebi/Water Heating/93276.jpg',id: 273,code: '93276',},
        {category: 'წყლის გამაცხელებელი ტენები',name: 'წყლის გამაცხელებელი ტენი',price: 1,description: 'Description for წყლის გამაცხელებელი ტენი',image: 'assets/tenebi/Water Heating/93325.jpg',id: 274,code: '93325',},
        {category: 'წყლის გამაცხელებელი ტენები',name: 'წყლის გამაცხელებელი ტენი',price: 1,description: 'Description for წყლის გამაცხელებელი ტენი',image: 'assets/tenebi/Water Heating/93326.jpg',id: 275,code: '93326',},
        {category: 'წყლის გამაცხელებელი ტენები',name: 'წყლის გამაცხელებელი ტენი',price: 1,description: 'Description for წყლის გამაცხელებელი ტენი',image: 'assets/tenebi/Water Heating/93332.jpg',id: 276,code: '93332',},
        {category: 'წყლის გამაცხელებელი ტენები',name: 'წყლის გამაცხელებელი ტენი',price: 1,description: 'Description for წყლის გამაცხელებელი ტენი',image: 'assets/tenebi/Water Heating/93431.jpg',id: 277,code: '93431',},
        {category: 'წყლის გამაცხელებელი ტენები',name: 'წყლის გამაცხელებელი ტენი',price: 1,description: 'Description for წყლის გამაცხელებელი ტენი',image: 'assets/tenebi/Water Heating/93433.jpg',id: 278,code: '93433',},
        {category: 'წყლის გამაცხელებელი ტენები',name: 'წყლის გამაცხელებელი ტენი',price: 1,description: 'Description for წყლის გამაცხელებელი ტენი',image: 'assets/tenebi/Water Heating/93525.jpg',id: 279,code: '93525',},
        {category: 'წყლის გამაცხელებელი ტენები',name: 'წყლის გამაცხელებელი ტენი',price: 1,description: 'Description for წყლის გამაცხელებელი ტენი',image: 'assets/tenebi/Water Heating/93574.jpg',id: 280,code: '93574',},
        {category: 'წყლის გამაცხელებელი ტენები',name: 'წყლის გამაცხელებელი ტენი',price: 1,description: 'Description for წყლის გამაცხელებელი ტენი',image: 'assets/tenebi/Water Heating/AQH10-1612.jpg',id: 281,code: 'AQH10-1612',},
        {category: 'წყლის გამაცხელებელი ტენები',name: 'წყლის გამაცხელებელი ტენი',price: 1,description: 'Description for წყლის გამაცხელებელი ტენი',image: 'assets/tenebi/Water Heating/RFC12-1618-230.jpg',id: 282,code: 'RFC12-1618-230',},
        {category: 'წყლის გამაცხელებელი ტენები',name: 'წყლის გამაცხელებელი ტენი',price: 1,description: 'Description for წყლის გამაცხელებელი ტენი',image: 'assets/tenebi/Water Heating/RFD10-27.jpg',id: 283,code: 'RFD10-27',},

        {category: 'სარეცხი მანქანის ტენები',name: 'სარეცხი მანქანის ტენი',price: 1,description: 'Description for სარეცხი მანქანის ტენი',image: 'assets/tenebi/Washing Machine/20363.jpg',id: 284,code: '20363',},
        {category: 'სარეცხი მანქანის ტენები',name: 'სარეცხი მანქანის ტენი',price: 1,description: 'Description for სარეცხი მანქანის ტენი',image: 'assets/tenebi/Washing Machine/20364.jpg',id: 285,code: '20364',},
        {category: 'სარეცხი მანქანის ტენები',name: 'სარეცხი მანქანის ტენი',price: 1,description: 'Description for სარეცხი მანქანის ტენი',image: 'assets/tenebi/Washing Machine/20365.jpg',id: 286,code: '20365',},
        {category: 'სარეცხი მანქანის ტენები',name: 'სარეცხი მანქანის ტენი',price: 1,description: 'Description for სარეცხი მანქანის ტენი',image: 'assets/tenebi/Washing Machine/20366.jpg',id: 287,code: '20366',},
        {category: 'სარეცხი მანქანის ტენები',name: 'სარეცხი მანქანის ტენი',price: 1,description: 'Description for სარეცხი მანქანის ტენი',image: 'assets/tenebi/Washing Machine/20411.jpg',id: 288,code: '20411',},
        {category: 'სარეცხი მანქანის ტენები',name: 'სარეცხი მანქანის ტენი',price: 1,description: 'Description for სარეცხი მანქანის ტენი',image: 'assets/tenebi/Washing Machine/93663.jpg',id: 289,code: '93663',},
        {category: 'სარეცხი მანქანის ტენები',name: 'სარეცხი მანქანის ტენი',price: 1,description: 'Description for სარეცხი მანქანის ტენი',image: 'assets/tenebi/Washing Machine/93676.jpg',id: 290,code: '93676',},
        {category: 'სარეცხი მანქანის ტენები',name: 'სარეცხი მანქანის ტენი',price: 1,description: 'Description for სარეცხი მანქანის ტენი',image: 'assets/tenebi/Washing Machine/93682.jpg',id: 291,code: '93682',},
        {category: 'სარეცხი მანქანის ტენები',name: 'სარეცხი მანქანის ტენი',price: 1,description: 'Description for სარეცხი მანქანის ტენი',image: 'assets/tenebi/Washing Machine/93684.jpg',id: 292,code: '93684',},
        {category: 'სარეცხი მანქანის ტენები',name: 'სარეცხი მანქანის ტენი',price: 1,description: 'Description for სარეცხი მანქანის ტენი',image: 'assets/tenebi/Washing Machine/93685.jpg',id: 293,code: '93685',},
        {category: 'სარეცხი მანქანის ტენები',name: 'სარეცხი მანქანის ტენი',price: 1,description: 'Description for სარეცხი მანქანის ტენი',image: 'assets/tenebi/Washing Machine/700422.jpg',id: 294,code: '700422',},
        {category: 'სარეცხი მანქანის ტენები',name: 'სარეცხი მანქანის ტენი',price: 1,description: 'Description for სარეცხი მანქანის ტენი',image: 'assets/tenebi/Washing Machine/700423.jpg',id: 295,code: '700423',},

        {category: 'ვენტილაციის ტენები',name: 'ვენტილაციის ტენი',price: 1,description: 'Description for ვენტილაციის ტენი',image: 'assets/tenebi/Ventilation/91965.jpg',id: 296,code: '91965',},
        {category: 'ვენტილაციის ტენები',name: 'ვენტილაციის ტენი',price: 1,description: 'Description for ვენტილაციის ტენი',image: 'assets/tenebi/Ventilation/91966.jpg',id: 297,code: '91966',},
        {category: 'ვენტილაციის ტენები',name: 'ვენტილაციის ტენი',price: 1,description: 'Description for ვენტილაციის ტენი',image: 'assets/tenebi/Ventilation/91967.jpg',id: 298,code: '91967',},
        {category: 'ვენტილაციის ტენები',name: 'ვენტილაციის ტენი',price: 1,description: 'Description for ვენტილაციის ტენი',image: 'assets/tenebi/Ventilation/91968.jpg',id: 299,code: '91968',},
        {category: 'ვენტილაციის ტენები',name: 'ვენტილაციის ტენი',price: 1,description: 'Description for ვენტილაციის ტენი',image: 'assets/tenebi/Ventilation/91969.jpg',id: 300,code: '91969',},
        {category: 'ვენტილაციის ტენები',name: 'ვენტილაციის ტენი',price: 1,description: 'Description for ვენტილაციის ტენი',image: 'assets/tenebi/Ventilation/91970.jpg',id: 301,code: '91970',},
        {category: 'ვენტილაციის ტენები',name: 'ვენტილაციის ტენი',price: 1,description: 'Description for ვენტილაციის ტენი',image: 'assets/tenebi/Ventilation/91971.jpg',id: 302,code: '91971',},
        {category: 'ვენტილაციის ტენები',name: 'ვენტილაციის ტენი',price: 1,description: 'Description for ვენტილაციის ტენი',image: 'assets/tenebi/Ventilation/93598.jpg',id: 303,code: '93598',},
        {category: 'ვენტილაციის ტენები',name: 'ვენტილაციის ტენი',price: 1,description: 'Description for ვენტილაციის ტენი',image: 'assets/tenebi/Ventilation/93599.jpg',id: 304,code: '93599',},
        {category: 'ვენტილაციის ტენები',name: 'ვენტილაციის ტენი',price: 1,description: 'Description for ვენტილაციის ტენი',image: 'assets/tenebi/Ventilation/93600.jpg',id: 305,code: '93600',},
        {category: 'ვენტილაციის ტენები',name: 'ვენტილაციის ტენი',price: 1,description: 'Description for ვენტილაციის ტენი',image: 'assets/tenebi/Ventilation/93605.jpg',id: 306,code: '93605',},
        // {category: 'ვენტილაციის ტენები',name: 'ვენტილაციის ტენი',price: 1,description: 'Description for ვენტილაციის ტენი',image: 'assets/tenebi/Ventilation/85300500(Ø8,5).jpg',id: 307,code: '85300500(Ø8,5)',},
        {category: 'ვენტილაციის ტენები',name: 'ვენტილაციის ტენი',price: 1,description: 'Description for ვენტილაციის ტენი',image: 'assets/tenebi/Ventilation/855001000.jpg',id: 308,code: '855001000',},
        {category: 'ვენტილაციის ტენები',name: 'ვენტილაციის ტენი',price: 1,description: 'Description for ვენტილაციის ტენი',image: 'assets/tenebi/Ventilation/855531500.jpg',id: 309,code: '855531500',},
      ],
    },
  ];
  protected categorysListEN: Home[] = [
    {
      categorys: [
        'Oven T.H.E',
        'Toster T.H.E',
        'Grill T.H.E',
        'Thermostate',
        'Coffe Machine T.H.E',
        'Industrial T.H.E',
        'Water Heating T.H.E',
        'Washing Machine T.H.E',
        'Ventilation T.H.E',
      ],
      items: [
        {
          category: 'Thermostate',
          name: 'Item 1',
          price: 1,
          description: 'Description for Item 1',
          image: 'assets/tenebi/_0a7f8855-ec78-4bc2-adbd-877be5fe02d3.jpeg',
          id: 1,
          code: '001',
        },
        {
          category: 'Toster T.H.E',
          name: 'Item 1',
          price: 1,
          description: 'Description for Item 1',
          image: 'assets/tenebi/_9071a48a-cbb9-431c-ac09-2ecdf344e0f1.jpeg',
          id: 3,
          code: '002',
        },
        {
          category: 'Toster T.H.E',
          name: 'Item 1',
          price: 1,
          description: 'Description for Item 1',
          image: 'assets/tenebi/_9071a48a-cbb9-431c-ac09-2ecdf344e0f1.jpeg',
          id: 4,
          code: '002',
        },
        {
          category: 'Oven T.H.E',
          name: 'Item 1',
          price: 1,
          description: 'Description for Item 1',
          image: 'assets/tenebi/_9071a48a-cbb9-431c-ac09-2ecdf344e0f1.jpeg',
          id: 7,
          code: '002',
        },
        {
          category: 'Thermostate',
          name: 'Item 1',
          price: 1,
          description: 'Description for Item 1',
          image: 'assets/tenebi/_9071a48a-cbb9-431c-ac09-2ecdf344e0f1.jpeg',
          id: 5,
          code: '002',
        },
        {
          category: 'Toster T.H.E',
          name: 'Item 1',
          price: 1,
          description: 'Description for Item 1',
          image: 'assets/tenebi/_9071a48a-cbb9-431c-ac09-2ecdf344e0f1.jpeg',
          id: 11,
          code: '002',
        },
        {
          category: 'Toster T.H.E',
          name: 'Item 1',
          price: 1,
          description: 'Description for Item 1',
          image: 'assets/tenebi/_9071a48a-cbb9-431c-ac09-2ecdf344e0f1.jpeg',
          id: 10,
          code: '002',
        },
        {
          category: 'Oven T.H.E',
          name: 'Item 1',
          price: 1,
          description: 'Description for Item 1',
          image: 'assets/tenebi/_9071a48a-cbb9-431c-ac09-2ecdf344e0f1.jpeg',
          id: 6,
          code: '002',
        },
        {
          category: 'Oven T.H.E',
          name: 'Item 1',
          price: 1,
          description: 'Description for Item 1',
          image: 'assets/tenebi/_9071a48a-cbb9-431c-ac09-2ecdf344e0f1.jpeg',
          id: 12,
          code: '002',
        },
        {
          category: 'Toster T.H.E',
          name: 'Item 1',
          price: 1,
          description: 'Description for Item 1',
          image: 'assets/tenebi/_9071a48a-cbb9-431c-ac09-2ecdf344e0f1.jpeg',
          id: 9,
          code: '002',
        },
        {
          category: 'Toster T.H.E',
          name: 'Item 1',
          price: 1,
          description: 'Description for Item 1',
          image: 'assets/tenebi/_9071a48a-cbb9-431c-ac09-2ecdf344e0f1.jpeg',
          id: 8,
          code: '002',
        },
        {
          category: 'Thermostate',
          name: 'Item 1',
          price: 1,
          description: 'Description for Item 1',
          image: 'assets/tenebi/_9071a48a-cbb9-431c-ac09-2ecdf344e0f1.jpeg',
          id: 2,
          code: '002',
        },
      ],
    },
  ];

  protected popularList: Popular[] = [
    {
      category: 'ვენტილაციის ტენები',
      name: 'სახელი',
      price: 5,
      description: 'პოპილარული',
      src: 'assets/tenebi/Ventilation/91970.jpg',
      id: 10000,
      code: '91970',
    },
    {
      category: 'ვენტილაციის ტენები',
      name: 'სახელი',
      price: 5,
      description: 'პოპილარული',
      src: 'assets/tenebi/Oven/1048B-F3.jpg',
      id: 10001,
      code: '1048B(F3)',
    },
    {
      category: 'ვენტილაციის ტენები',
      name: 'სახელი',
      price: 5,
      description: 'პოპილარული',
      src: 'assets/tenebi/Oven/20813-F3.jpg',
      id: 10002,
      code: '20813(F3)',
    },
    {
      category: 'ვენტილაციის ტენები',
      name: 'სახელი',
      price: 5,
      description: 'პოპილარული',
      src: 'assets/tenebi/Oven/1151-F2.jpg',
      id: 10003,
      code: '1151(F2)',
    },
    {
      category: 'ვენტილაციის ტენები',
      name: 'სახელი',
      price: 5,
      description: 'პოპილარული',
      src: 'assets/tenebi/Oven/24204-F2.jpg',
      id: 10005,
      code: '24204-F2',
    },
    {
      category: 'ვენტილაციის ტენები',
      name: 'სახელი',
      price: 5,
      description: 'პოპილარული',
      src: 'assets/tenebi/Oven/25090-F2.jpg',
      id: 10006,
      code: '25090-F2',
    },
    {
      category: 'ვენტილაციის ტენები',
      name: 'სახელი',
      price: 10007,
      description: 'პოპილარული',
      src: 'assets/tenebi/Oven/24987-F3.jpg',
      id: 10007,
      code: '24987-F3',
    },
    {
      category: 'ვენტილაციის ტენები',
      name: 'სახელი',
      price: 10008,
      description: 'პოპილარული',
      src: 'assets/tenebi/Oven/25089-F3.jpg',
      id: 10008,
      code: '25089-F3',
    },
    {
      category: 'ვენტილაციის ტენები',
      name: 'სახელი',
      price: 10009,
      description: 'პოპილარული',
      src: 'assets/tenebi/Oven/25091-F3.jpg',
      id: 10009,
      code: '25091-F3',
    },
    {
      category: 'ვენტილაციის ტენები',
      name: 'სახელი',
      price: 1010,
      description: 'პოპილარული',
      src: 'assets/tenebi/Oven/70055-F1.jpg',
      id: 1010,
      code: '70055-F1',
    },
    {
      category: 'ვენტილაციის ტენები',
      name: 'სახელი',
      price: 1011,
      description: 'პოპილარული',
      src: 'assets/tenebi/Oven/24764-F3.jpg',
      id: 1011,
      code: '24764-F3',
    },
    {
      category: 'ვენტილაციის ტენები',
      name: 'სახელი',
      price: 1012,
      description: 'პოპილარული',
      src: 'assets/tenebi/Oven/24206-F3.jpg',
      id: 1012,
      code: '24206-F3',
    },
    {
      category: 'ვენტილაციის ტენები',
      name: 'სახელი',
      price: 1013,
      description: 'პოპილარული',
      src: 'assets/tenebi/Oven/24086.jpg',
      id: 1013,
      code: '24086',
    },
    {
      category: 'ვენტილაციის ტენები',
      name: 'სახელი',
      price: 1014,
      description: 'პოპილარული',
      src: 'assets/tenebi/Oven/24884-F3.jpg',
      id: 1014,
      code: '24884-F3',
    },
    {
      category: 'ვენტილაციის ტენები',
      name: 'სახელი',
      price: 1,
      description: 'პოპილარული',
      src: 'assets/tenebi/Industrial/93582.jpg',
      id: 1015,
      code: '93582',
    },
    {
      category: 'ვენტილაციის ტენები',
      name: 'სახელი',
      price: 5,
      description: 'პოპილარული',
      src: 'assets/tenebi/Washing Machine/93684.jpg',
      id: 1016,
      code: '93684',
    },
    {
      category: 'ვენტილაციის ტენები',
      name: 'სახელი',
      price: 5,
      description: 'პოპილარული',
      src: 'assets/tenebi/Industrial/92764.jpg',
      id: 1017,
      code: '92764',
    },
    {
      category: 'ვენტილაციის ტენები',
      name: 'სახელი',
      price: 5,
      description: 'პოპილარული',
      src: 'assets/tenebi/Industrial/93505.jpg',
      id: 1018,
      code: '93505',
    },
    {
      category: 'ვენტილაციის ტენები',
      name: 'სახელი',
      price: 5,
      description: 'პოპილარული',
      src: 'assets/tenebi/Coffe/92481-1.jpg',
      id: 1019,
      code: '92481-1',
    },
    {
      category: 'ვენტილაციის ტენები',
      name: 'სახელი',
      price: 5,
      description: 'პოპილარული',
      src: 'assets/tenebi/Industrial/93641.jpg',
      id: 1020,
      code: '93641',
    },
    {
      category: 'ვენტილაციის ტენები',
      name: 'სახელი',
      price: 5,
      description: 'პოპილარული',
      src: 'assets/tenebi/Coffe/93704.jpg',
      id: 1021,
      code: '93704',
    },
    {
      category: 'ვენტილაციის ტენები',
      name: 'სახელი',
      price: 5,
      description: 'პოპილარული',
      src: 'assets/tenebi/Coffe/92571.jpg',
      id: 1022,
      code: '92571',
    },
    {
      category: 'ვენტილაციის ტენები',
      name: 'სახელი',
      price: 5,
      description: 'პოპილარული',
      src: 'assets/tenebi/Coffe/92655.jpg',
      id: 1023,
      code: '92655',
    },
    {
      category: 'ვენტილაციის ტენები',
      name: 'სახელი',
      price: 5,
      description: 'პოპილარული',
      src: 'assets/tenebi/Oven/24971-F3.jpg',
      id: 1024,
      code: '24971-F3',
    },
    {
      category: 'ვენტილაციის ტენები',
      name: 'სახელი',
      price: 5,
      description: 'პოპილარული',
      src: 'assets/tenebi/Oven/24975-F3.jpg',
      id: 1025,
      code: '24975-F3',
    },
    {
      category: 'ვენტილაციის ტენები',
      name: 'სახელი',
      price: 5,
      description: 'პოპილარული',
      src: 'assets/tenebi/Termostat/RTD10-28.jpg',
      id: 1026,
      code: 'RTD1C-28',
    },
    {
      category: 'ვენტილაციის ტენები',
      name: 'სახელი',
      price: 5,
      description: 'პოპილარული',
      src: 'assets/tenebi/Oven/1159-F2.jpg',
      id: 1027,
      code: '1159-F2',
    },
    {
      category: 'ვენტილაციის ტენები',
      name: 'სახელი',
      price: 5,
      description: 'პოპილარული',
      src: 'assets/tenebi/Industrial/91588.jpg',
      id: 1028,
      code: '91588',
    },
    {
      category: 'ვენტილაციის ტენები',
      name: 'სახელი',
      price: 5,
      description: 'პოპილარული',
      src: 'assets/tenebi/Industrial/92136.jpg',
      id: 1029,
      code: '92136',
    },
    {
      category: 'ვენტილაციის ტენები',
      name: 'სახელი',
      price: 5,
      description: 'პოპილარული',
      src: 'assets/tenebi/Oven/1161-F3.jpg',
      id: 1030,
      code: '1161-F3',
    },
    {
      category: 'ვენტილაციის ტენები',
      name: 'სახელი',
      price: 5,
      description: 'პოპილარული',
      src: 'assets/tenebi/Oven/22986.jpg',
      id: 1031,
      code: '22986',
    },
    {
      category: 'ვენტილაციის ტენები',
      name: 'სახელი',
      price: 5,
      description: 'პოპილარული',
      src: 'assets/tenebi/Coffe/91684.jpg',
      id: 1032,
      code: '91684',
    },
    {
      category: 'ვენტილაციის ტენები',
      name: 'სახელი',
      price: 5,
      description: 'პოპილარული',
      src: 'assets/tenebi/Coffe/91683.jpg',
      id: 1033,
      code: '91683',
    },
    {
      category: 'ვენტილაციის ტენები',
      name: 'სახელი',
      price: 5,
      description: 'პოპილარული',
      src: 'assets/tenebi/Coffe/24533.jpg',
      id: 1034,
      code: '24533',
    },
    {
      category: 'ვენტილაციის ტენები',
      name: 'სახელი',
      price: 5,
      description: 'პოპილარული',
      src: 'assets/tenebi/Termostat/TR-1-7027.jpg',
      id: 1035,
      code: 'TR-1/7027',
    },
    {
      category: 'ვენტილაციის ტენები',
      name: 'სახელი',
      price: 5,
      description: 'პოპილარული',
      src: 'assets/tenebi/Termostat/TRS-657527.jpg',
      id: 1036,
      code: 'TRS/657527',
    },
    {
      category: 'ვენტილაციის ტენები',
      name: 'სახელი',
      price: 5,
      description: 'პოპილარული',
      src: 'assets/tenebi/Industrial/91976.jpg',
      id: 1037,
      code: '91976',
    },
    {
      category: 'ვენტილაციის ტენები',
      name: 'სახელი',
      price: 5,
      description: 'პოპილარული',
      src: 'assets/tenebi/Industrial/92705.jpg',
      id: 1038,
      code: '92705',
    },
    {
      category: 'ვენტილაციის ტენები',
      name: 'სახელი',
      price: 5,
      description: 'პოპილარული',
      src: 'assets/tenebi/Washing Machine/93676.jpg',
      id: 1039,
      code: '93676',
    },
  ];
  itemAdded: EventEmitter<Item> = new EventEmitter<Item>();

  constructor(private translateService: TranslateService) {}

  getAllCategoryList(): Home[] {
    let lang: string | undefined;
    this.translateService.getCurrentLanguage().subscribe((language) => {
      lang = language;
    });
    return lang && lang.toLowerCase() === 'en'
      ? this.categorysListEN
      : this.categorysList;
  }
  getAllPopularList(): Popular[] {
    return this.popularList;
  }
  getAllPopularId(id:number):Popular|undefined{
    return this.popularList.find(sitem=>sitem.id===id);
  }
  getAllCategoryListEn(): Home[] {
    return this.categorysListEN;
  }

  getAllCategoryId(id: number): Item | undefined {
    for (const home of this.categorysList) {
      const item = home.items.find((item) => item.id === id);
      if (item) {
        return item;
      }
    }
    return undefined;
  }

  getItemsForCategory(categoryIndex: number): Item[] {
    const category = this.categorysList[0].categorys[categoryIndex];
    return this.categorysList[0].items.filter(
      (item) => item.category === category
    );
  }

  addItem(newItem: Item): void {
    console.log('Adding item:', newItem);
    const categoryIndex = this.categorysList[0].categorys.findIndex(
      (category) => category === newItem.category
    );
    newItem.id = this.categorysList[0].items.length + 1;
    this.categorysList[0].items.push(newItem);
    this.itemAdded.emit(newItem);
  }

  updateCategoryList(language: string): Observable<Home[]> {
    if (language && language.toLowerCase() === 'en') {
      return of(this.getAllCategoryListEn());
    } else {
      return of(this.getAllCategoryList());
    }
  }
}
